### ISSUE TITLE
Packages crypto-base and crypto-md5 giving errors

### ISSUE THREAD

**Issue by simison** [Vincit/slurp#1]
I just quickly set this up and those packages gave me some errors, so I went dirty and simply Git cloned them directly to packages folder. Now meteor is happy.

I might look more into this later.

```
ReferenceError: CryptoJS is not defined
     at Package (packages/crypto-md5/md5.js:9)
     at Package (packages/crypto-md5/md5.js:173)
     at packages/crypto-md5.js:190:4
     at packages/crypto-md5.js:197:3
...
```

**Comment by lasseli** [comment]
I couldn't reproduce this issue when I just now set this up in an environment that didn't have any requirements installed previously.
